import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Transcription Call",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html data-lt-installed="true" lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<Providers> {children}</Providers>
			</body>
		</html>
	);
}
